service: anonymous-location
image: hschne/anonymous-location

servers:
  web:
    hosts:
      - 159.69.216.175
    labels:
      traefik.http.routers.anonymouslocation_secure.rule: Host(`anonymouslocation.com`)
      traefik.http.routers.anonymouslocation_secure.entrypoints: websecure
      traefik.http.routers.anonymouslocation_secure.rule: Host(`anonymouslocation.com`)
      traefik.http.routers.anonymouslocation_secure.tls: true
      traefik.http.routers.anonymouslocation_secure.tls.certresolver: letsencrypt
    options:
      network: "private"

registry:
  username: hschne
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    HOSTNAME: anonymouslocation.com
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY
    - MAPTILER_KEY

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
    network: "private"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "support@anonymouslocation.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
